### ISSUE TITLE
Improved Conditional Flow Rule

### ISSUE THREAD

**Issue by MuffinMICHI** [camunda/bpmnlint-plugin-camunda#5]
#### The rule should detect the following modeling patterns

The proposed rule should detect, if a condition for every outgoing path of a gateway is set. The rule should display an error immediately after modelling the outgoing sequence paths of a gateway.

#### How does the rule improve the BPMN diagram?

The benefit of this rule is, that people immediately see, if their outgoing paths of a gateway are configured or not. If a condition is not set, the mistake mostly occurs after deploying and executing the process for the first time. This rule prevents, that process with gateways are modeled, where the outgoing paths of a gateway do not have a condition defined. Furthermore this rule helps people to learn, how the decisions at a gateway are defined, since every outgoing path should contain a condition.

#### Rule Details

* Name: gateway-conditions
* Default notification level: `error`

#### What alternatives did you consider? 

An alternative to this propose is the existing rule "conditional-flows.js".
But if a gateway with outgoing sequence flows is modeled, this rule does not tell you, that the conditions for the paths are not set. Only if you set a condition for the first path, it tells you, that the conditions for the other paths are not set. The missing conditions are not displayed right away.

**Comment by nikku** [comment]
I've added a work-in-progress PR on this: https://github.com/camunda/bpmnlint-plugin-camunda/pull/6.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/bpmnlint-plugin-camunda/pull/6.
